name: Documentation Issue
description: Report an error or suggest an improvement in the docs
labels: [documentation]
title: "[docs] "

body:
  - type: textarea
    id: issue
    attributes:
      label: What’s wrong or missing?
      description: Tell us what needs to be fixed or clarified.
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Page and/or section
      description: e.g., overview > introduction > Key Features of Shadboard
